config <- list(
    threshold = 0.005,
    ppm = 5,
    mode = c("Proteomics", "Metabolomics"),
    Digestion_site = "trypsin",
    missedCleavages = 0:1,
    adducts = c("M+H"),
    Modifications = list(
      fixed = NULL,
      fixmod_position = NULL,
      variable = NULL,
      varmod_position = NULL
    ),
    Substitute_AA = NULL,
    Decoy_search = TRUE,
    Decoy_adducts = c(
      "M+ACN+H",
      "M+IsoProp+H",
      "M+DMSO+H",
      "M+Co",
      "M+Ag",
      "M+Cu",
      "M+He",
      "M+Ne",
      "M+Ar",
      "M+Kr",
      "M+Xe",
      "M+Rn"
    ),
    Decoy_mode = "isotope",
    mzrange = c(700, 4000),
    Database_stats = FALSE,
    adjust_score = FALSE,
    Bypass_generate_spectrum = FALSE,
    peptide_ID_filter = 2,
    plot_ion_image = FALSE,
    parallel = detectCores(),
    spectra_segments_per_file = 4,
    Segmentation = c(
      "spatialKMeans",
      "spatialShrunkenCentroids",
      "Virtual_segmentation",
      "none",
      "def_file"
    )[1],
    Segmentation_def = "Segmentation_def.csv",
    Segmentation_ncomp = "auto-detect",
    Segmentation_variance_coverage = 0.8,
    preprocess = list(
      force_preprocess = TRUE,
      use_preprocessRDS = FALSE,
      smoothSignal = list(method = c("disable", "gaussian", "sgolay", "ma")[1]),
      reduceBaseline = list(method = c("disable", "locmin", "median")[1]),
      peakPick = list(method = c("adaptive", "diff", "sd", "mad", "quantile", "filter", "cwt")[4]),
      peakAlign = list(
        tolerance = 5,
        units = "ppm",
        level = c("local", "global")[1],
        method = c("enable", "disable")[1]
      ),
      peakFilter = list(freq.min = 0.05),
      normalize = list(
        method = c("disable", "rms", "tic", "reference")[1],
        mz = NULL
      )
    ),
    Smooth_range = 1,
    Virtual_segmentation = FALSE,
    Virtual_segmentation_rankfile = NULL,
    Rotate_IMG = NULL,
    Spectrum_validate = TRUE,
    score_method = "SQRTP",
    deconv_peaklist = "New",
    plot_cluster_image_maxretry = 2,
    plot_cluster_image_overwrite = FALSE,
    smooth.image = "gaussian",
    componentID_colname = "Peptide",
    ClusterID_colname = "Protein",
    Protein_desc_of_interest = c("Crystallin", "Actin"),
    Protein_desc_of_exclusion = NULL,
    plot_unique_component = TRUE,
    FDR_cutoff = 0.05,
    use_top_rank = NULL,
    plot_matching_score = FALSE,
    Component_plot_coloure = "mono",
    cluster_color_scale = "blackwhite",
    plot_layout = "line",
    export_Header_table = TRUE,
    export_footer_table = TRUE,
    attach_summary_cluster = TRUE,
    pixel_size_um = 50,
    img_brightness = 100,
    cluster_rds_path = NULL,
    remove_score_outlier = FALSE,
    Plot_score_IQR_cutoff = 0.75,
    Plot_score_abs_cutoff = -0.1,
    mzAlign_runs = "TopNfeature_mean"
)