FROM hitmap:dev_hitmap AS build

FROM r-base:4.4.1

COPY --from=build /usr/local/lib/R/site-library /usr/local/lib/R/site-library

RUN apt-get update && apt-get install -y \
        default-jdk-headless \
        texlive \
        libnss-winbind \
        dirmngr \
        gnupg \
        winbind \
        apt-transport-https \
        ca-certificates \
        software-properties-common \
    && rm -r /var/lib/apt/lists/* \
    && rm -r /var/cache/apt/*
